server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          username:
          password:
        #          uri: file:///Users/namgon/Documents/git-local-repo
          uri: https://github.com/ng-lee/spring-cloud-msa-config

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh